use recherche_emploi;

insert into typesfichiers(nom) values ('Photo Candidat');
insert into typesfichiers(nom) values ('Logo Entreprise');
insert into typesfichiers(nom) values ('CV');


insert into typescontrat(nom) values ('CDI');
insert into typescontrat(nom) values ('CDD');
insert into typescontrat(nom) values ('Stage');
insert into typescontrat(nom) values ('Alternance');

insert into villes(nom,departement) values ("SAINT-QUENTIN",2);
insert into villes(nom,departement) values ("GRASSE",6);
insert into villes(nom,departement) values ("ANTIBES",6);
insert into villes(nom,departement) values ("CANNES",6);
insert into villes(nom,departement) values ("NICE",6);
insert into villes(nom,departement) values ("CHARLEVILLE-MEZIERES",8);
insert into villes(nom,departement) values ("TROYES",10);
insert into villes(nom,departement) values ("NARBONNE",11);
insert into villes(nom,departement) values ("AIX-EN-PROVENCE",13);
insert into villes(nom,departement) values ("MARSEILLE",13);
insert into villes(nom,departement) values ("ARLES",13);
insert into villes(nom,departement) values ("CAEN",14);
insert into villes(nom,departement) values ("LA ROCHELLE",17);
insert into villes(nom,departement) values ("BOURGES",18);
insert into villes(nom,departement) values ("DIJON",21);
insert into villes(nom,departement) values ("BESANCON",25);
insert into villes(nom,departement) values ("VALENCE",26);
insert into villes(nom,departement) values ("EVREUX",27);
insert into villes(nom,departement) values ("QUIMPER",29);
insert into villes(nom,departement) values ("BREST",29);
insert into villes(nom,departement) values ("NIMES",30);
insert into villes(nom,departement) values ("TOULOUSE",31);
insert into villes(nom,departement) values ("BORDEAUX",33);
insert into villes(nom,departement) values ("PESSAC",33);
insert into villes(nom,departement) values ("MERIGNAC",33);
insert into villes(nom,departement) values ("BEZIERS",34);
insert into villes(nom,departement) values ("MONTPELLIER",34);
insert into villes(nom,departement) values ("RENNES",35);
insert into villes(nom,departement) values ("TOURS",37);
insert into villes(nom,departement) values ("GRENOBLE",38);
insert into villes(nom,departement) values ("SAINT-ETIENNE",42);
insert into villes(nom,departement) values ("NANTES",44);
insert into villes(nom,departement) values ("SAINT-NAZAIRE",44);
insert into villes(nom,departement) values ("ORLEANS",45);
insert into villes(nom,departement) values ("CHOLET",49);
insert into villes(nom,departement) values ("ANGERS",49);
insert into villes(nom,departement) values ("REIMS",51);
insert into villes(nom,departement) values ("LAVAL",53);
insert into villes(nom,departement) values ("NANCY",54);
insert into villes(nom,departement) values ("LORIENT",56);
insert into villes(nom,departement) values ("VANNES",56);
insert into villes(nom,departement) values ("METZ",57);
insert into villes(nom,departement) values ("ROUBAIX",59);
insert into villes(nom,departement) values ("VILLENEUVE-D'ASCQ",59);
insert into villes(nom,departement) values ("LILLE",59);
insert into villes(nom,departement) values ("TOURCOING",59);
insert into villes(nom,departement) values ("DUNKERQUE",59);
insert into villes(nom,departement) values ("BEAUVAIS",60);
insert into villes(nom,departement) values ("CALAIS",62);
insert into villes(nom,departement) values ("CLERMONT-FERRAND",63);
insert into villes(nom,departement) values ("PAU",64);
insert into villes(nom,departement) values ("PERPIGNAN",66);
insert into villes(nom,departement) values ("STRASBOURG",67);
insert into villes(nom,departement) values ("COLMAR",68);
insert into villes(nom,departement) values ("MULHOUSE",68);
insert into villes(nom,departement) values ("VENISSIEUX",69);
insert into villes(nom,departement) values ("LYON",69);
insert into villes(nom,departement) values ("VILLEURBANNE",69);
insert into villes(nom,departement) values ("LE MANS",72);
insert into villes(nom,departement) values ("CHAMBERY",73);
insert into villes(nom,departement) values ("ANNECY",74);
insert into villes(nom,departement) values ("PARIS",75);
insert into villes(nom,departement) values ("ROUEN",76);
insert into villes(nom,departement) values ("LE HAVRE",76);
insert into villes(nom,departement) values ("CHELLES",77);
insert into villes(nom,departement) values ("SARTROUVILLE",78);
insert into villes(nom,departement) values ("VERSAILLES",78);
insert into villes(nom,departement) values ("NIORT",79);
insert into villes(nom,departement) values ("AMIENS",80);
insert into villes(nom,departement) values ("MONTAUBAN",82);
insert into villes(nom,departement) values ("HYERES",83);
insert into villes(nom,departement) values ("FREJUS",83);
insert into villes(nom,departement) values ("TOULON",83);
insert into villes(nom,departement) values ("LA SEYNE-SUR-MER",83);
insert into villes(nom,departement) values ("AVIGNON",84);
insert into villes(nom,departement) values ("LA ROCHE-SUR-YON",85);
insert into villes(nom,departement) values ("POITIERS",86);
insert into villes(nom,departement) values ("LIMOGES",87);
insert into villes(nom,departement) values ("BELFORT",90);
insert into villes(nom,departement) values ("EVRY",91);
insert into villes(nom,departement) values ("NEUILLY-SUR-SEINE",92);
insert into villes(nom,departement) values ("CLAMART",92);
insert into villes(nom,departement) values ("ISSY-LES-MOULINEAUX",92);
insert into villes(nom,departement) values ("RUEIL-MALMAISON",92);
insert into villes(nom,departement) values ("ANTONY",92);
insert into villes(nom,departement) values ("LEVALLOIS-PERRET",92);
insert into villes(nom,departement) values ("BOULOGNE-BILLANCOURT",92);
insert into villes(nom,departement) values ("ASNIERES-SUR-SEINE",92);
insert into villes(nom,departement) values ("COLOMBES",92);
insert into villes(nom,departement) values ("COURBEVOIE",92);
insert into villes(nom,departement) values ("CLICHY",92);
insert into villes(nom,departement) values ("NANTERRE",92);
insert into villes(nom,departement) values ("SEVRAN",93);
insert into villes(nom,departement) values ("MONTREUIL",93);
insert into villes(nom,departement) values ("AULNAY-SOUS-BOIS",93);
insert into villes(nom,departement) values ("SAINT-DENIS",93);
insert into villes(nom,departement) values ("NOISY-LE-GRAND",93);
insert into villes(nom,departement) values ("AUBERVILLIERS",93);
insert into villes(nom,departement) values ("PANTIN",93);
insert into villes(nom,departement) values ("BONDY",93);
insert into villes(nom,departement) values ("EPINAY-SUR-SEINE",93);
insert into villes(nom,departement) values ("DRANCY",93);
insert into villes(nom,departement) values ("LE BLANC-MESNIL",93);
insert into villes(nom,departement) values ("FONTENAY-SOUS-BOIS",94);
insert into villes(nom,departement) values ("SAINT-MAUR-DES-FOSSES",94);
insert into villes(nom,departement) values ("VILLEJUIF",94);
insert into villes(nom,departement) values ("VITRY-SUR-SEINE",94);
insert into villes(nom,departement) values ("CHAMPIGNY-SUR-MARNE",94);
insert into villes(nom,departement) values ("IVRY-SUR-SEINE",94);
insert into villes(nom,departement) values ("MAISONS-ALFORT",94);
insert into villes(nom,departement) values ("CRETEIL",94);
insert into villes(nom,departement) values ("CERGY",95);
insert into villes(nom,departement) values ("ARGENTEUIL",95);
insert into villes(nom,departement) values ("SARCELLES",95);
insert into villes(nom,departement) values ("ABYMES",971);
insert into villes(nom,departement) values ("FORT-DE-FRANCE",972);
insert into villes(nom,departement) values ("CAYENNE",973);
insert into villes(nom,departement) values ("SAINT-ANDRE",974);
insert into villes(nom,departement) values ("SAINT-DENIS",974);
insert into villes(nom,departement) values ("SAINT-LOUIS",974);
insert into villes(nom,departement) values ("SAINT-PAUL",974);
insert into villes(nom,departement) values ("SAINT-PIERRE",974);
insert into villes(nom,departement) values ("TAMPON",974);
insert into villes(nom,departement) values ("MAMOUDZOU",976);
